### ISSUE TITLE
HLA- prediction with one-step-GUI

### ISSUE THREAD

**Issue by marthaspn** [MannLabs/PeptDeep-HLA#1]
Will the HLA-prediction model be available through a one-step-GUI in the near future?

**Comment by jalew188** [comment]
Dear @marthanik, I still don't have time to develop a GUI for peptdeep_HLA, but I now make notebooks available on Colab, see https://github.com/MannLabs/PeptDeep-HLA/blob/master/nbs/HLA1_transfer.ipynb. You can use Colab for transfer learning and download the predicted HLA sequences. I hope it helps.

**Comment by marthaspn** [comment]
Dear Dr. Zeng,

thanks for the update. I will have a look with some collaborators more
familiar with coding.

Best regards,
Martha

Στις Πέμ 29 Δεκ 2022 στις 2:53 μ.μ., ο/η Zeng, Wen-Feng <
***@***.***> έγραψε:
