### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'sequence'

### ISSUE THREAD

**Issue by Vectolyser** [MannLabs/PeptDeep-HLA#8]
Hello，I want to predict HLA peptides from my own tsv file，but it always report error with the content as shown in the title（The file was generated by FragPipe and I just changed the name of the required column to 'sequence').Even if I just created a file with the format as same as “sequence_table”，it still reports error. Can you please help？

**Comment by jalew188** [comment]
@Vectolyser There are some bugs in CLI commands, I am working on this now.
